name: adios_cube_stats
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip
  - astropy
  - numpy
  - boost
  - matplotlib
  - compilers
  - openmpi
  - adios2 # no-mpi version
  - pip:
    - python-casacore
